name: Rust

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install 1.76
        run: rustup install 1.76

      - name: Set default toolchain
        run: rustup default 1.76

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose --test integration_tests -- --show-output
